### PR TITLE
Hello world

### PR DESCRIPTION
**Pull request by yajo**
Initial version, with tests, docs and all that stuff.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What is this?

**Comment by yajo** [comment]
Something we need for several projects, mostly docker images.

**Comment by pedrobaeza** [comment]
OK, what's mistery...

**Comment by yajo** [comment]
No mistery 😊 

We are reworking many infrastructure pieces to be able to solve unstabilities as new versions arise. This makes us need to tag releases in several components. For docker images specifically we need to be able to tag the latest one, which needs to be properly detected. But there are other use cases such as copier templates, ansible collections, etc.

There's a common need of handling versions, so I decided to strip that out in a separate library.

**Comment by pedrobaeza** [comment]
Ok, thanks for the extra explanations

**Pull request merged**
